name = "MacroDataFetchers"
uuid = "fab5017f-b469-41f8-8728-3d672a68268f"
authors = ["Enrico Wegner"]
version = "1.0.0-DEV"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
